id: PBBB9344B
initial_creation_type: ocr
source_metadata:
  volumes:
    f994ea4163e64b5487be136bc932a2b7:
      base_file: v042.txt
      image_group_id: I1PD95887
      title: ''
      total_pages: 1712
      volume_number: 42
